
names_dict = {"Sao Paulo": ["São Paolo", "San Paolo", "San Paulo", "São Pãulo"],
              "Bombay": ["Mumbai", "Bumbay"], 
              "Moscow": ["Moskva", "Moskva"],
              "Istanbul": ["İstanbul", "Constantinople"],
              "Tokyo": ["Tōkyō"],
              "Xian": ["Xi'an", "Xī'ān"],
              "Beijing": ["Běijīng"],
              "Hong Kong": ["Hongkong"],
              "Kiev": ["Kyiv", "Kiew"],
              "Calcutta": ["Kolkata"], 
              "Bogotá": ["Bogotá"],
              "Tianjin": ["Tiānjīn"],
              "Haerbin": ["Harbin"], 
              "Shenyang": ["Shěnyáng"],
              "Bucuresti": ["Bucharest"], 
              "Wuhan": ["Wǔhàn"],
              "Madras": ["Chennai"],
              "Pusan": ["Busan"],
              "Haerbin": ["Harbin"],
              "Pyong Yang": ["Pyongyang"],
              "Chengdu": ["Chéngdū"],
              "St Petersburg": ["Saint Petersburg", "St. Petersburg"]}